// THIS FILE IS FOR LOCAL DEVELOPMENT ONLY.
// It is ignored by Git.
// For Vercel deployment, this file is generated by `generate-config.sh`.

window.env = {
    SUPABASE_URL: 'https://nxhoyxvuyehqnnrqhyom.supabase.co',
    SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54aG95eHZ1eWVocW5ucnFoeW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDg2OTEsImV4cCI6MjA3MDc4NDY5MX0.pRUwKmZOxBOQCWdJLJLPgIP_YDkXp5iMPUBN2RpHb5I'
};
